const DBSchema = {
  servers: {
    tableName: "servers",
    id: "id",
    createdAt: "created_at",
    name: "name",
    iconUrl: "icon_url",
    livekitUrl: "livekit_url",
    livekitApiKey: "livekit_api_key",
    livekitSecretKey: "livekit_secret_key",
  },
  users: {
    tableName: "users",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    username: "username",
    displayName: "display_name",
    publicKey: "public_key",
    stableId: "stable_id",
    isBanned: "is_banned",
    isServerAdmin: "is_server_admin",
    isChannelManager: "is_channel_manager",
    canCreateTokens: "can_create_tokens",
    isMuted: "is_muted",
    isDeafened: "is_deafened",
  },
  channels: {
    tableName: "channels",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    name: "name",
    channelType: "channel_type",
  },
  tokens: {
    tableName: "tokens",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    token: "token",
    userId: "user_id",
    expiresAt: "expires_at",
  },
  invites: {
    tableName: "invites",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    code: "code",
    isServerAdmin: "is_server_admin",
    isChannelManager: "is_channel_manager",
    canCreateTokens: "can_create_tokens",
    maxUses: "max_uses",
    uses: "uses",
    expiresAt: "expires_at",
  },
  authChallenges: {
    tableName: "auth_challenges",
    nonce: "nonce",
    expiresAt: "expires_at",
    publicKey: "public_key",
  },
};

export default DBSchema;
