const DBSchema = {
  servers: {
    tableName: "servers",
    id: "id",
    createdAt: "created_at",
    name: "name",
    iconUrl: "icon_url",
    livekitUrl: "livekit_url",
    livekitApiKey: "livekit_api_key",
    livekitSecretKey: "livekit_secret_key",
  },
  users: {
    tableName: "users",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    username: "username",
    displayName: "display_name",
    publicKey: "public_key",
    stableId: "stable_id",
    isBanned: "is_banned",
    isServerAdmin: "is_server_admin",
    isChannelManager: "is_channel_manager",
    canCreateTokens: "can_create_tokens",
    isMuted: "is_muted",
    isDeafened: "is_deafened",
    chatPublicKey: "chat_public_key",
  },
  messages: {
    tableName: "messages",
    id: "id",
    createdAt: "created_at",
    channelId: "channel_id",
    senderId: "sender_id",
    ciphertext: "ciphertext",
    nonce: "nonce",
    signature: "signature",
    keyVersion: "key_version",
    editedAt: "edited_at",
  },
  dmMessages: {
    tableName: "dm_messages",
    id: "id",
    createdAt: "created_at",
    senderId: "sender_id",
    recipientId: "recipient_id",
    ciphertext: "ciphertext",
    nonce: "nonce",
    signature: "signature",
    keyVersion: "key_version",
    editedAt: "edited_at",
  },
  channelKeyring: {
    tableName: "channel_keyring",
    id: "id",
    createdAt: "created_at",
    channelId: "channel_id",
    keyVersion: "key_version",
    userId: "user_id",
    wrappedBy: "wrapped_by",
    ephemeralPublicKey: "ephemeral_public_key",
    ciphertext: "ciphertext",
    nonce: "nonce",
  },
  channels: {
    tableName: "channels",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    name: "name",
    channelType: "channel_type",
  },
  notifications: {
    tableName: "notifications",
    id: "id",
    createdAt: "created_at",
    userId: "user_id",
    channelId: "channel_id",
    messageId: "message_id",
    senderId: "sender_id",
    readAt: "read_at",
  },
  invites: {
    tableName: "invites",
    id: "id",
    createdAt: "created_at",
    serverId: "server_id",
    code: "code",
    isServerAdmin: "is_server_admin",
    isChannelManager: "is_channel_manager",
    canCreateTokens: "can_create_tokens",
    maxUses: "max_uses",
    uses: "uses",
    expiresAt: "expires_at",
  },
  messageReactions: {
    tableName: "message_reactions",
    messageId: "message_id",
    userId: "user_id",
    emoji: "emoji",
    createdAt: "created_at",
  },
  dmMessageReactions: {
    tableName: "dm_message_reactions",
    messageId: "message_id",
    userId: "user_id",
    emoji: "emoji",
    createdAt: "created_at",
  },
};

export default DBSchema;
